import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({ weight: '400', subsets: ['latin'], display: 'swap', style: ['normal', 'italic'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
